modLoader="javafml" #mandatory
loaderVersion="[1,)" #mandatory
license="All Rights Reserved"

[[mods]] #mandatory
modId="danconomy" #mandatory
version="1.1.1" #mandatory
displayName="DanConomy" #mandatory
description='''
A Simple Economy Mod for Minecraft
'''

[[dependencies.danconomy]] #optional
modId="neoforge" #mandatory
type="required" #mandatory
versionRange="[21.1.209,)" #mandatory
ordering="NONE"
side="BOTH"

[[dependencies.danconomy]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

#[features.danconomy]
#openGLVersion="[3.2,)"
